version: '2'
services:
  server:
    build: ./server
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - NODE_PORT=3000
    volumes:
      - ./server:/usr/src/app
    command: nodemon app.js
